## Calculating density

The following functions will be useful:

0. `gsw.p_from_z(z, lat)`  (i.e. if needed)
1. `gsw.SA_from_SP(SP, p, lon, lat)`
2. `gsw.CT_from_pt(SA, pt)`
3. `gsw.rho(SA, CT, p)`

SP = practical salinity, SA = absolute salinity, p = pressure (dbar), CT = conservative temperature, pt = potential temperature.

In [1]:
import numpy
import gsw

### Broadcasting and gsw

In [6]:
z = [-10., -50., -125., -250., -600., -1000.]
lat = 4.
gsw.p_from_z(z, lat)

array([   10.05572704,    50.28354425,   125.73185732,   251.54028663,
         604.2099135 ,  1007.9900587 ])

In [7]:
z = [-10., -50., -125., -250., -600., -1000.]
lat = [4., 4., 4., 4., 4., 4.]
gsw.p_from_z(z, lat)

array([   10.05572704,    50.28354425,   125.73185732,   251.54028663,
         604.2099135 ,  1007.9900587 ])

In [11]:
z = numpy.ones((3,4))
lat = numpy.ones((3,4))
gsw.p_from_z(z, lat)

array([[-1.00552148, -1.00552148, -1.00552148, -1.00552148],
       [-1.00552148, -1.00552148, -1.00552148, -1.00552148],
       [-1.00552148, -1.00552148, -1.00552148, -1.00552148]])