Still need to figure out:
* Running mean

In [86]:
import numpy
import pandas
import xray; print(xray.__version__)

0.5.0


### Reading data

In [87]:
#infile = '/Users/damienirving/Downloads/Data/va_ERAInterim_500hPa_2006-030day-runmean_native.nc'
infile = '/Users/damienirving/Downloads/Data/sic_ERAInterim_surface_1993-1994-daily_native-shextropics30.nc'
dset = xray.open_dataset(infile)

In [88]:
dset

<xray.Dataset>
Dimensions:    (latitude: 81, longitude: 480, time: 730)
Coordinates:
  * longitude  (longitude) float32 0.0 0.75 1.5 2.25 3.0 3.75 4.5 5.25 6.0 ...
  * latitude   (latitude) float32 -90.0 -89.25 -88.5 -87.75 -87.0 -86.25 ...
  * time       (time) datetime64[ns] 1993-01-01T18:00:00 1993-01-02T18:00:00 ...
Data variables:
    sic        (time, latitude, longitude) float64 nan nan nan nan nan nan ...
Attributes:
    CDI: Climate Data Interface version 1.5.3 (http://code.zmaw.de/projects/cdi)
    Conventions: CF-1.0
    history: Mon Jun 22 16:13:38 2015: cdo seldate,1993-01-01,1994-12-31 -sellonlatbox,0,359.9,-90,-30 sic_ERAInterim_surface_daily_native.nc sic_ERAInterim_surface_1993-1994-daily_native-shextropics30.nc
Thu Mar 19 13:05:10 2015: ncatted -O -a axis,time,c,c,T /mnt/meteo0/data/simmonds/dbirving/ERAInterim/data/sic_ERAInterim_surface_daily_native.nc
Thu Mar 19 11:42:24 2015: ncatted -O -a missing_value,sic,o,f,-32767. /mnt/meteo0/data/simmonds/dbirving/ERAInterim

In [89]:
darray = dset['sic']
darray

<xray.DataArray 'sic' (time: 730, latitude: 81, longitude: 480)>
[28382400 values with dtype=float64]
Coordinates:
  * latitude   (latitude) float32 -90.0 -89.25 -88.5 -87.75 -87.0 -86.25 ...
  * longitude  (longitude) float32 0.0 0.75 1.5 2.25 3.0 3.75 4.5 5.25 6.0 ...
  * time       (time) datetime64[ns] 1993-01-01T18:00:00 1993-01-02T18:00:00 ...
Attributes:
    standard_name: sea_ice_fraction
    long_name: sea_ice_fraction
    units: (0 - 1)

In [90]:
#data
#swap_dict = {'time': 'latitude'}
#print data.dims
#data.swap_dims(swap_dict)
#print data.dims

In [91]:
darray.values

array([[[ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan,  nan,  nan, ...,  nan,  nan,  nan],
        ..., 
        [  0.,   0.,   0., ...,   0.,   0.,   0.],
        [  0.,   0.,   0., ...,   0.,   0.,   0.],
        [  0.,   0.,   0., ...,   0.,   0.,   0.]],

       [[ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan,  nan,  nan, ...,  nan,  nan,  nan],
        ..., 
        [  0.,   0.,   0., ...,   0.,   0.,   0.],
        [  0.,   0.,   0., ...,   0.,   0.,   0.],
        [  0.,   0.,   0., ...,   0.,   0.,   0.]],

       [[ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan,  nan,  nan, ...,  nan,  nan,  nan],
        ..., 
        [  0.,   0.,   0., ...,   0.,   0.,   0.],
        [  0.,   0.,   0., ...,   0.,   0.,   0.],
        [  0.,   0.,   0., ...,   0.,   0.,   0.]],

       ..., 
       [[ nan,  nan, 

In [93]:
# Get the order of the dimensions
darray.dims

(u'time', u'latitude', u'longitude')

In [94]:
darray['time'].attrs

OrderedDict([(u'standard_name', u'time')])

#### Missing values

[This page](http://xray.readthedocs.org/en/stable/io.html) suggests that xray recognises the `_FillValue` attribute.

However, once you've read the data in the `_FillValue` attribute disappears. When you write the output file there is no `_FillValue` attribute and any missing values appear as `NaNf` when you ncdump. This doesn't appear to be a problem for cdo or iris.

In [95]:
missing_data = darray.sel(longitude=3.75, latitude=-81).values
numpy.isnan(missing_data[0])

True

### Climatologies

You can group by `month`, `day`, `dayofyear`, `dayofweek` and whatever else belongs to the [`pandas.DatetimeIndex` class](http://pandas.pydata.org/pandas-docs/dev/generated/pandas.DatetimeIndex.html).

##### Monthly

In [96]:
mon_clim = darray.groupby('time.month').mean('time')

In [97]:
mon_clim

<xray.DataArray 'sic' (month: 12, latitude: 81, longitude: 480)>
array([[[ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan,  nan,  nan, ...,  nan,  nan,  nan],
        ..., 
        [  0.,   0.,   0., ...,   0.,   0.,   0.],
        [  0.,   0.,   0., ...,   0.,   0.,   0.],
        [  0.,   0.,   0., ...,   0.,   0.,   0.]],

       [[ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan,  nan,  nan, ...,  nan,  nan,  nan],
        ..., 
        [  0.,   0.,   0., ...,   0.,   0.,   0.],
        [  0.,   0.,   0., ...,   0.,   0.,   0.],
        [  0.,   0.,   0., ...,   0.,   0.,   0.]],

       [[ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan,  nan,  nan, ...,  nan,  nan,  nan],
        ..., 
        [  0.,   0.,   0., ...,   0.,   0.,   0.],
        [  0.,   0.,   0., ...,   0.,   0.,   0.],
        [  0.,   0.,  

#### Daily

(Feb 28 is day 59. In a leap year, Feb 29 is day 60.)

In [98]:
day_clim = darray.groupby('time.dayofyear').mean('time')
day_clim

<xray.DataArray 'sic' (dayofyear: 365, latitude: 81, longitude: 480)>
array([[[ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan,  nan,  nan, ...,  nan,  nan,  nan],
        ..., 
        [  0.,   0.,   0., ...,   0.,   0.,   0.],
        [  0.,   0.,   0., ...,   0.,   0.,   0.],
        [  0.,   0.,   0., ...,   0.,   0.,   0.]],

       [[ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan,  nan,  nan, ...,  nan,  nan,  nan],
        ..., 
        [  0.,   0.,   0., ...,   0.,   0.,   0.],
        [  0.,   0.,   0., ...,   0.,   0.,   0.],
        [  0.,   0.,   0., ...,   0.,   0.,   0.]],

       [[ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan,  nan,  nan, ...,  nan,  nan,  nan],
        ..., 
        [  0.,   0.,   0., ...,   0.,   0.,   0.],
        [  0.,   0.,   0., ...,   0.,   0.,   0.],
        [  0.,   

#### Daily anomaly 

In [99]:
dummy_dset = xray.Dataset({'foo': ('time', numpy.random.randn(4000)),
                           'time': pandas.date_range('2000-01-01', periods=4000)})
clim = dummy_dset.groupby('time.dayofyear').mean()
anom = dummy_dset.groupby('time.dayofyear') - clim

In [100]:
dummy_dset

<xray.Dataset>
Dimensions:  (time: 4000)
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 ...
Data variables:
    foo      (time) float64 0.5978 -0.9033 -1.506 0.06015 -0.1679 2.212 ...

In [101]:
clim

<xray.Dataset>
Dimensions:    (dayofyear: 366)
Coordinates:
  * dayofyear  (dayofyear) int64 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 ...
Data variables:
    foo        (dayofyear) float64 -0.1735 0.4935 -0.4261 0.106 -0.4842 ...

In [102]:
anom

<xray.Dataset>
Dimensions:    (time: 4000)
Coordinates:
    dayofyear  (time) int32 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 ...
  * time       (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 ...
Data variables:
    foo        (time) float64 0.7713 -1.397 -1.08 -0.04582 0.3163 2.059 ...

### Selection

It's possible to select a single dimension value or a slice of values:

In [103]:
slice(-70, -50)

slice(-70, -50, None)

In [105]:
darray.sel(time=('1993-03-25'))

<xray.DataArray 'sic' (time: 1, latitude: 81, longitude: 480)>
array([[[ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan,  nan,  nan, ...,  nan,  nan,  nan],
        ..., 
        [  0.,   0.,   0., ...,   0.,   0.,   0.],
        [  0.,   0.,   0., ...,   0.,   0.,   0.],
        [  0.,   0.,   0., ...,   0.,   0.,   0.]]])
Coordinates:
  * latitude   (latitude) float32 -90.0 -89.25 -88.5 -87.75 -87.0 -86.25 ...
  * longitude  (longitude) float32 0.0 0.75 1.5 2.25 3.0 3.75 4.5 5.25 6.0 ...
  * time       (time) datetime64[ns] 1993-03-25T18:00:00
Attributes:
    standard_name: sea_ice_fraction
    long_name: sea_ice_fraction
    units: (0 - 1)

In [106]:
darray.sel(time=slice('1993-03-25', '1993-04-25'))

<xray.DataArray 'sic' (time: 32, latitude: 81, longitude: 480)>
array([[[ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan,  nan,  nan, ...,  nan,  nan,  nan],
        ..., 
        [  0.,   0.,   0., ...,   0.,   0.,   0.],
        [  0.,   0.,   0., ...,   0.,   0.,   0.],
        [  0.,   0.,   0., ...,   0.,   0.,   0.]],

       [[ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan,  nan,  nan, ...,  nan,  nan,  nan],
        ..., 
        [  0.,   0.,   0., ...,   0.,   0.,   0.],
        [  0.,   0.,   0., ...,   0.,   0.,   0.],
        [  0.,   0.,   0., ...,   0.,   0.,   0.]],

       [[ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan,  nan,  nan, ...,  nan,  nan,  nan],
        ..., 
        [  0.,   0.,   0., ...,   0.,   0.,   0.],
        [  0.,   0.,   0., ...,   0.,   0.,   0.],
        [  0.,   0.,   

For an arbitrary list of dimension values, you need to provide the exact date/time value (for single dates xray/pandas can guess what you meant).

In [107]:
darray['latitude'][0:20]

<xray.DataArray 'latitude' (latitude: 20)>
array([-90.  , -89.25, -88.5 , -87.75, -87.  , -86.25, -85.5 , -84.75,
       -84.  , -83.25, -82.5 , -81.75, -81.  , -80.25, -79.5 , -78.75,
       -78.  , -77.25, -76.5 , -75.75], dtype=float32)
Coordinates:
  * latitude  (latitude) float32 -90.0 -89.25 -88.5 -87.75 -87.0 -86.25 ...
Attributes:
    standard_name: latitude
    long_name: latitude
    units: degrees_north
    axis: Y

In [108]:
darray.sel(latitude=[-89.25, -81])

<xray.DataArray 'sic' (time: 730, latitude: 2, longitude: 480)>
array([[[ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan,  nan,  nan, ...,  nan,  nan,  nan]],

       [[ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan,  nan,  nan, ...,  nan,  nan,  nan]],

       [[ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan,  nan,  nan, ...,  nan,  nan,  nan]],

       ..., 
       [[ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan,  nan,  nan, ...,  nan,  nan,  nan]],

       [[ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan,  nan,  nan, ...,  nan,  nan,  nan]],

       [[ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan,  nan,  nan, ...,  nan,  nan,  nan]]])
Coordinates:
  * latitude   (latitude) float32 -89.25 -81.0
  * longitude  (longitude) float32 0.0 0.75 1.5 2.25 3.0 3.75 4.5 5.25 6.0 ...
  * time       (time) datetime64[ns] 1993-01-01T18:00:00 1993-01-02T18:00:00 ...
Attributes:
    standard_name: sea_ice_fraction
    long_name: sea_ice_fraction

In [109]:
darray['time'][0:10]

<xray.DataArray 'time' (time: 10)>
array(['1993-01-02T05:00:00.000000000+1100',
       '1993-01-03T05:00:00.000000000+1100',
       '1993-01-04T05:00:00.000000000+1100',
       '1993-01-05T05:00:00.000000000+1100',
       '1993-01-06T05:00:00.000000000+1100',
       '1993-01-07T05:00:00.000000000+1100',
       '1993-01-08T05:00:00.000000000+1100',
       '1993-01-09T05:00:00.000000000+1100',
       '1993-01-10T05:00:00.000000000+1100',
       '1993-01-11T05:00:00.000000000+1100'], dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 1993-01-01T18:00:00 1993-01-02T18:00:00 ...
Attributes:
    standard_name: time

In [110]:
darray.sel(time=[numpy.datetime64('1993-01-04T05:00:00.000000000+1100'),
               numpy.datetime64('1993-01-10T05:00:00.000000000+1100')])

<xray.DataArray 'sic' (time: 2, latitude: 81, longitude: 480)>
array([[[ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan,  nan,  nan, ...,  nan,  nan,  nan],
        ..., 
        [  0.,   0.,   0., ...,   0.,   0.,   0.],
        [  0.,   0.,   0., ...,   0.,   0.,   0.],
        [  0.,   0.,   0., ...,   0.,   0.,   0.]],

       [[ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan,  nan,  nan, ...,  nan,  nan,  nan],
        ..., 
        [  0.,   0.,   0., ...,   0.,   0.,   0.],
        [  0.,   0.,   0., ...,   0.,   0.,   0.],
        [  0.,   0.,   0., ...,   0.,   0.,   0.]]])
Coordinates:
  * latitude   (latitude) float32 -90.0 -89.25 -88.5 -87.75 -87.0 -86.25 ...
  * longitude  (longitude) float32 0.0 0.75 1.5 2.25 3.0 3.75 4.5 5.25 6.0 ...
  * time       (time) datetime64[ns] 1993-01-03T18:00:00 1993-01-09T18:00:00
Attributes:
    standard_name: sea_ice_fraction

In [111]:
darray.sel(time=[numpy.datetime64('1993-01-04'),
               numpy.datetime64('1993-01-10')])

ValueError: not all values found in index 'time'

#### Maths / stats

#### Basic stats along a dimension

In [112]:
outdata = darray.mean(dim=['latitude', 'longitude'])

#### Running mean

I need to figure out how to apply the pandas [moving (rolling) statistics](http://pandas.pydata.org/pandas-docs/stable/computation.html#moving-rolling-statistics-moments) to an `xray.DataArray`. [This page](http://xray.readthedocs.org/en/stable/pandas.html) talks about how I might do that.

In [121]:
outdata.attrs = darray.attrs

In [122]:
outdata.attrs

OrderedDict([(u'standard_name', u'sea_ice_fraction'), (u'long_name', u'sea_ice_fraction'), (u'units', u'(0 - 1)')])

In [123]:
outdata.to_netcdf('test_xray.nc', format='NETCDF3_CLASSIC')

AttributeError: 'DataArray' object has no attribute 'to_netcdf'

#### From scratch

In [32]:
hello = numpy.arange(0, 730)
print hello.shape

(730,)


In [33]:
d = {}
d['time'] = data['time']
d['hello'] = (['time'], hello)

dset_out = xray.Dataset(d)

In [34]:
dset_out.attrs

OrderedDict()

In [101]:
dset_out['time'].attrs

OrderedDict([(u'standard_name', u'time')])

In [104]:
dset_out['hello'].attrs = {'standard_name': 'hello', 'units': 'smiles'}

In [105]:
dset_out

<xray.Dataset>
Dimensions:  (time: 730)
Coordinates:
  * time     (time) datetime64[ns] 1993-01-01T18:00:00 1993-01-02T18:00:00 ...
Data variables:
    hello    (time) int64 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 ...

In [106]:
dset_out['hello'].attrs

OrderedDict([('units', 'smiles'), ('standard_name', 'hello')])

In [36]:
words = 'hello_world'
words.split(' ')

['hello_world']